#!/bin/sh
#
# This is a wrapper script to build all examples and update the documents
#
for i in \
    shared_ptr \
    shared_ptr_wrapper
do
    echo $i:
    (cd $i; sh ./RUNME)
    echo
done
cat README.md.template */README.md > README.md
