#!/bin/sh
#
# This is a wrapper script to build all examples and update the documents
#
. common/common.sh

SUBDIRS="range_based_for_loop \
         range_based_for_loop_custom_begin_end \
         std_move \
         std_unique_ptr \
         std_shared_ptr \
         std_shared_ptr_wrapper"

for i in $SUBDIRS
do
    echo
    log $i:
    (cd $i; sh ./RUNME; ./example) | sed 's/^/    /g'
done

cp README.md.template README.md
for i in $SUBDIRS
    cat $i/README.md >> README.md
do
