#!/bin/sh
#
# This is a wrapper script to build all examples and update the documents
#
. common/common.sh
for i in \
    unique_ptr \
    shared_ptr \
    shared_ptr_wrapper
do
    echo
    log $i:
    (cd $i; sh ./RUNME; ./example) | sed 's/^/    /g'
done
cat README.md.template */README.md > README.md
