NAME=example

TARGET_OBJECTS=main.o

EXTRA_CXXFLAGS=

%.o: %.cpp
	@echo $(CXX) $(EXTRA_CXXFLAGS) $(CXXFLAGS) -c -o $@ $<
	@$(CXX) $(EXTRA_CXXFLAGS) $(CXXFLAGS) -c -o $@ $<

#
# link
#
TARGET=$(NAME)$(EXE)
$(TARGET): $(TARGET_OBJECTS)
	$(CXX) $(TARGET_OBJECTS) $(LDLIBS) -o $(TARGET)

#
# To force clean and avoid "up to date" warning.
#
.PHONY: clean
.PHONY: clobber

clean:
	rm *.o

clobber: clean

all: $(TARGET) 
